import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  ensureReviewBrokerConfigDefaults,
  type EnsureReviewBrokerConfigDefaultsOptions,
} from './config-defaults.js';

const DEFAULT_EXTENSION_FILENAME = 'tandem-review.mjs';

export interface InstallTandemReviewExtensionOptions
  extends Omit<EnsureReviewBrokerConfigDefaultsOptions, 'projectRoot'> {
  projectRoot?: string;
  extensionPath?: string;
  force?: boolean;
}

export interface InstallTandemReviewExtensionResult {
  projectRoot: string;
  extensionPath: string;
  configPath: string;
  extensionCreated: boolean;
  extensionUpdated: boolean;
  configCreated: boolean;
  configUpdated: boolean;
}

function renderExtensionEntrypoint(): string {
  return `/**
 * Tandem review-gate extension for this project.
 *
 * Auto-generated by tandem-review-install.
 */

import {
  createTandemReviewExtension,
  createBrokerTransportAdapter,
  ensureReviewBrokerConfigDefaults,
} from 'review-broker-extension';
import { startInProcessBrokerClient } from 'review-broker-client';

const BROKER_DB_PATH = process.env.TANDEM_BROKER_DB?.trim() || undefined;
const AUTHOR_ID = process.env.TANDEM_AUTHOR_ID ?? 'auto-agent';
const BLOCKED_POLICY = process.env.TANDEM_REVIEW_BLOCKED_POLICY === 'intervene'
  ? 'intervene'
  : 'auto-loop';
const REVIEW_WAIT_TIMEOUT_MS = Number.parseInt(process.env.TANDEM_REVIEW_WAIT_TIMEOUT_MS ?? '', 10);
const REVIEW_WAIT_POLL_INTERVAL_MS = Number.parseInt(process.env.TANDEM_REVIEW_WAIT_POLL_INTERVAL_MS ?? '', 10);

function optionalNonNegativeMs(value) {
  return Number.isFinite(value) && value >= 0 ? value : undefined;
}

function optionalPositiveMs(value) {
  return Number.isFinite(value) && value > 0 ? value : undefined;
}

ensureReviewBrokerConfigDefaults({
  projectRoot: process.cwd(),
});

const { client } = startInProcessBrokerClient({
  ...(BROKER_DB_PATH ? { dbPath: BROKER_DB_PATH } : {}),
  cwd: process.cwd(),
  handleSignals: false,
});

export default createTandemReviewExtension({
  blockedPolicy: BLOCKED_POLICY,
  reviewWaitTimeoutMs: optionalNonNegativeMs(REVIEW_WAIT_TIMEOUT_MS),
  reviewWaitPollIntervalMs: optionalPositiveMs(REVIEW_WAIT_POLL_INTERVAL_MS),
  transport: createBrokerTransportAdapter({
    client,
    cwd: process.cwd(),
    authorId: AUTHOR_ID,
  }),
});
`;
}

export function installTandemReviewExtension(
  options: InstallTandemReviewExtensionOptions = {},
): InstallTandemReviewExtensionResult {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd());
  const extensionPath = path.resolve(
    options.extensionPath ??
      path.join(projectRoot, '.gsd', 'extensions', DEFAULT_EXTENSION_FILENAME),
  );

  const extensionContent = renderExtensionEntrypoint();

  let extensionCreated = false;
  let extensionUpdated = false;

  if (!existsSync(extensionPath)) {
    mkdirSync(path.dirname(extensionPath), { recursive: true });
    writeFileSync(extensionPath, extensionContent, 'utf8');
    extensionCreated = true;
    extensionUpdated = true;
  } else {
    const existing = readFileSync(extensionPath, 'utf8');
    if (existing !== extensionContent && options.force === true) {
      writeFileSync(extensionPath, extensionContent, 'utf8');
      extensionUpdated = true;
    }
  }

  const configResult = ensureReviewBrokerConfigDefaults({
    projectRoot,
    ...(options.configPath ? { configPath: options.configPath } : {}),
    ...(options.providerName ? { providerName: options.providerName } : {}),
    ...(options.workerCommand ? { workerCommand: options.workerCommand } : {}),
    ...(options.workerScriptPath ? { workerScriptPath: options.workerScriptPath } : {}),
  });

  return {
    projectRoot,
    extensionPath,
    configPath: configResult.configPath,
    extensionCreated,
    extensionUpdated,
    configCreated: configResult.created,
    configUpdated: configResult.updated,
  };
}
